name: Java
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - java/**

jobs:
  push:
    name: "esdock:java_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
        
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./java
          # Elige la carpeta correcta según el rango del tag
          file: |
            ${{ matrix.tag >= 16 && matrix.tag <= 20 && 'amd' || matrix.tag >= 21 && matrix.tag }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/zastinian/esdock:java_${{ matrix.tag }}
